"""Report generator — creates Markdown, HTML, and JSON reports."""
import json
from datetime import datetime
from pathlib import Path
from typing import Optional

from rich.console import Console

class ReportGenerator:
    def __init__(self, target: str, results: list, output_dir: Path, console: Console):
        self.target = target
        self.results = results
        self.output_dir = Path(output_dir)
        self.console = console

    def generate(self, format: str = "markdown") -> Path:
        """Generate report in specified format."""
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

        if format == "json":
            return self._generate_json(timestamp)
        elif format == "html":
            return self._generate_html(timestamp)
        else:
            return self._generate_markdown(timestamp)

    def _generate_json(self, timestamp: str) -> Path:
        data = {
            "target": self.target,
            "timestamp": timestamp,
            "scanners_run": len(self.results),
            "results": [],
        }

        for r in self.results:
            data["results"].append({
                "scanner": r.scanner_name,
                "target": r.target,
                "success": r.success,
                "parsed_data": r.parsed_data,
                "errors": r.errors,
                "timestamp": r.timestamp,
            })

        path = self.output_dir / "report.json"
        path.write_text(json.dumps(data, indent=2, default=str))
        return path

    def _generate_html(self, timestamp: str) -> Path:
        md_content = self._build_markdown_content(timestamp)

        html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Recon Report — {self.target}</title>
    <style>
        * {{ margin: 0; padding: 0; box-sizing: border-box; }}
        body {{ font-family: 'Segoe UI', system-ui, sans-serif; max-width: 900px; margin: 0 auto; padding: 2rem; background: #0d1117; color: #c9d1d9; line-height: 1.6; }}
        h1 {{ color: #58a6ff; border-bottom: 2px solid #30363d; padding-bottom: 0.5rem; }}
        h2 {{ color: #79c0ff; margin-top: 2rem; border-left: 3px solid #58a6ff; padding-left: 0.75rem; }}
        h3 {{ color: #d2a8ff; }}
        .meta {{ background: #161b22; padding: 1rem; border-radius: 8px; margin-bottom: 2rem; border: 1px solid #30363d; }}
        .meta span {{ color: #58a6ff; }}
        pre {{ background: #161b22; padding: 1rem; border-radius: 6px; overflow-x: auto; border: 1px solid #30363d; font-size: 0.9rem; }}
        code {{ background: #1c2128; padding: 0.15rem 0.4rem; border-radius: 3px; font-size: 0.85rem; }}
        .finding {{ background: #161b22; border-left: 3px solid #3fb950; padding: 0.75rem 1rem; margin: 0.5rem 0; border-radius: 0 6px 6px 0; }}
        .warning {{ border-left-color: #d29922; }}
        .error {{ border-left-color: #f85149; }}
        table {{ width: 100%; border-collapse: collapse; margin: 1rem 0; }}
        th, td {{ padding: 0.5rem; text-align: left; border-bottom: 1px solid #30363d; }}
        th {{ background: #161b22; color: #58a6ff; }}
        .footer {{ margin-top: 3rem; text-align: center; color: #484f58; font-size: 0.85rem; }}
    </style>
</head>
<body>
    <h1>🔍 OSINT Recon Report</h1>
    <div class="meta">
        <p><span>Target:</span> {self.target}</p>
        <p><span>Generated:</span> {timestamp}</p>
        <p><span>Scanner Count:</span> {len(self.results)}</p>
        <p><span>Tool:</span> recon-cli v0.1.0</p>
    </div>
    {self._build_html_sections()}
    <div class="footer">
        <p>Generated by recon-cli | Charles H Lewis II</p>
    </div>
</body>
</html>"""

        path = self.output_dir / "report.html"
        path.write_text(html)
        return path

    def _generate_markdown(self, timestamp: str) -> Path:
        content = self._build_markdown_content(timestamp)
        path = self.output_dir / "report.md"
        path.write_text(content)
        return path

    def _build_markdown_content(self, timestamp: str) -> str:
        lines = [
            f"# 🔍 OSINT Recon Report",
            f"",
            f"**Target:** `{self.target}`  ",
            f"**Generated:** {timestamp}  ",
            f"**Tool:** recon-cli v0.1.0  ",
            f"**Scanners Run:** {len(self.results)}",
            "",
            "---",
            "",
        ]

        summary_lines = []
        for r in self.results:
            status = "✅" if r.success else "❌"
            count = len(r.parsed_data) if r.parsed_data else 0
            summary_lines.append(f"| {r.scanner_name} | {status} | {count} items | {'; '.join(r.errors) if r.errors else '—'} |")

        lines.extend([
            "## Summary",
            "",
            "| Scanner | Status | Findings | Notes |",
            "|---------|:------:|----------|-------|",
        ] + summary_lines + ["", "---", ""])

        for r in self.results:
            status = "✅" if r.success else "❌"
            lines.extend([
                f"## {r.scanner_name} {status}",
                "",
            ])

            if r.errors:
                for err in r.errors:
                    lines.append(f"> ⚠️ {err}")
                lines.append("")

            if r.parsed_data:
                if isinstance(r.parsed_data, dict):
                    for key, value in r.parsed_data.items():
                        if isinstance(value, list):
                            lines.append(f"### {key}")
                            lines.append("")
                            for item in value[:100]:  # Cap at 100 items
                                if isinstance(item, dict):
                                    lines.append(f"- `{json.dumps(item, default=str)}`")
                                else:
                                    lines.append(f"- `{item}`")
                            if len(value) > 100:
                                lines.append(f"- ... and {len(value) - 100} more")
                            lines.append("")
                        elif isinstance(value, dict):
                            lines.append(f"### {key}")
                            lines.append(f"```json")
                            lines.append(json.dumps(value, indent=2, default=str)[:2000])
                            lines.append("```")
                            lines.append("")
                        else:
                            lines.append(f"- **{key}:** {value}")
                            lines.append("")
                else:
                    lines.append(f"```")
                    lines.append(str(r.parsed_data)[:5000])
                    lines.append("```")
                    lines.append("")
            else:
                lines.append("*No data collected.*")
                lines.append("")

            lines.append("---")
            lines.append("")

        lines.extend([
            "## Raw Data",
            "",
            f"All raw scanner output available in `raw/` directory.",
            "",
            "---",
            f"*Report generated by recon-cli — Charles H Lewis II*",
        ])

        return "\n".join(lines)

    def _build_html_sections(self) -> str:
        sections = []
        for r in self.results:
            status_class = "finding" if r.success else "error"
            status_label = "✅ Complete" if r.success else "❌ Failed"

            content = ""
            if r.parsed_data:
                content = f"<pre><code>{json.dumps(r.parsed_data, indent=2, default=str)[:5000]}</code></pre>"
            if r.errors:
                for err in r.errors:
                    content += f'<div class="finding warning">⚠️ {err}</div>'

            sections.append(f"""
            <div class="{status_class}">
                <h3>{r.scanner_name} — {status_label}</h3>
                {content or '<p style="color:#484f58;">No data collected.</p>'}
            </div>
            """)

        return "\n".join(sections)
