[tool.poetry]
name = "recon-cli"
version = "0.1.0"
description = "Automated OSINT reconnaissance pipeline"
authors = ["Charles H Lewis II <chl@chl1225.com>"]
readme = "README.md"
packages = [{include = "recon_cli"}]

[tool.poetry.scripts]
recon-cli = "recon_cli.cli:main"

[tool.poetry.dependencies]
python = "^3.10"
rich = "^13.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
